name: Release

on:
  release:
    types: [published]


jobs:
  upload_release:
    name: Build and upload release to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install nox
        run: pip install nox

      - name: Build and upload to PyPI
        run: nox -s upload_release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
